packages:
  - client
  - server
onlyBuiltDependencies:
  - esbuild
overrides:
  "@trpc/server": "11.1.2"
  "@trpc/client": "11.1.2"
  "@trpc/tanstack-react-query": "11.1.2"
  "@tanstack/react-query": "^5.74.7"
